name = "js-slot-machine-worker"
account_id = "ed920024c248189f2b6ba738be024dee"
workers_dev = true
compatibility_date = "2024-09-14"

main = "src/workers/shuffle-worker.ts"

[env.production]
name = "js-slot-machine-worker-prod"